### ISSUE TITLE
Jak rozumět licenci v kontextu komerčního použití?

### ISSUE THREAD

**Issue by avolny** [seznam/small-e-czech#1]
Dobrý den,

rádi bychom model použili jako základ pro finetuning v projektu pro klienta a není nám jasné jak rozumět licenci. Na konci Readme zmiňujete, že model poskytujete i ke komerčnímu použití, ale pokud to chápeme správně, tak zvolená licence (CC 4 ShareAlike) nám neumožňuje daný software/produkt klientovi poskytovat pod jinou licencí, než touto, pokud v něm model zahrneme. Nebo ve chvíli, kdy je model použit pouze jako base pro další pretraining a finetuning, tak se výsledného modelu licence netýká?

Mockrát díky za odpověď i za zveřejnění modelu!

**Comment by nimral** [comment]
Dobrý den,

děkujeme za podnět, pořešíme s právním.

**Comment by nimral** [comment]
Dobrý den,

rozhodli jsme se model zveřejnit pod volnější licencí CC BY 4.0, což striktně vzato není odpověď na vaši otázku (na tu si osobně netroufám), ale snad vám to usnadní rozhodování, zda model použít.

Díky za trpělivost a přejeme úspěšný finetuning

**Comment by avolny** [comment]
Vynikající, mockrát děkujeme za úpravu licence!!!
